"""first migration

Revision ID: 3b5bafd5b4fc
Revises: 
Create Date: 2024-10-08 19:25:25.036663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5bafd5b4fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tg_chat_id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tg_user_id')
    )
    op.create_table('user_chat',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.tg_chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.tg_user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chat')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
